name: html_editor_enhanced
description: HTML rich text editor for Android, iOS, and Web, using the Summernote library.
  Enhanced with critical bug fixes and support for callbacks, plugins, dark mode, and much more.
version: 1.8.0
homepage: https://github.com/tneotia/html-editor-enhanced

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  # webview plugin
  flutter_inappwebview: ^5.3.1+1
  # plugin for Dart/JS interoperability on Web platform
  js: ^0.6.3
  # plugin to get webview's visible fraction for keyboard height adjustment
  visibility_detector: ^0.2.0
  # plugin to get when the keyboard is hidden via back (Android)
  # or "done" (iOS) to reset the editor's height
  flutter_keyboard_visibility: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/summernote.html
    - assets/summernote-no-plugins.html
    - assets/summernote-lite.min.css
    - assets/summernote-lite-dark.css
    - assets/summernote-lite.min.js
    - assets/jquery.min.js
    - assets/font/summernote.eot
    - assets/font/summernote.ttf
    - assets/font/summernote.woff
    - assets/font/summernote.woff2
    - assets/plugins/additional-text-tags/summernote-add-text-tags.css
    - assets/plugins/additional-text-tags/summernote-add-text-tags.js
    - assets/plugins/summernote-emoji/summernote-ext-emoji-ajax.css
    - assets/plugins/summernote-emoji/summernote-ext-emoji-ajax.js
    - assets/plugins/summernote-case-converter/summernote-case-converter.js
    - assets/plugins/summernote-list-styles/summernote-list-styles.js
    - assets/plugins/summernote-list-styles/summernote-list-styles.css
    - assets/plugins/summernote-rtl/summernote-ext-rtl.js
    - assets/plugins/summernote-at-mention/bundle.js
    - assets/plugins/summernote-codewrapper/summernote-ext-codewrapper.min.js
    - assets/plugins/summernote-file/summernote-file.js
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
